name: newbee_talk_mk2
description: "뉴비톡톡mk2 리팩토링 프로젝트"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get: ^4.6.6
  supabase_flutter: ^2.4.0
  flutter_dotenv: ^5.1.0
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  http: ^1.2.1
  image_picker: ^1.0.7
  font_awesome_flutter: ^10.7.0
  flutter_naver_map: ^1.2.2
  geolocator: ^11.0.0
  daum_postcode_search: ^0.0.2
  flutter_inappwebview: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env
    - assets/fonts/

  fonts:
    - family: PretendardStatic
      fonts:
        - asset: assets/fonts/pretendard_static/Pretendard-Black.ttf
        - asset: assets/fonts/pretendard_static/Pretendard-Bold.ttf
        - asset: assets/fonts/pretendard_static/Pretendard-ExtraBold.ttf
        - asset: assets/fonts/pretendard_static/Pretendard-ExtraLight.ttf
        - asset: assets/fonts/pretendard_static/Pretendard-Light.ttf
        - asset: assets/fonts/pretendard_static/Pretendard-Medium.ttf
        - asset: assets/fonts/pretendard_static/Pretendard-Regular.ttf
        - asset: assets/fonts/pretendard_static/Pretendard-SemiBold.ttf
        - asset: assets/fonts/pretendard_static/Pretendard-Thin.ttf

    - family: PretendardVariable
      fonts:
        - asset: assets/fonts/pretendard_variable/PretendardVariable.ttf